<?php

namespace App\Supports;

class Constant
{
    const AC_ASSET = 1;

    const AC_LIABILITY = 2;

    const AC_EQUITY = 3;

    const AC_REVENUE = 4;

    const AC_EXPENSE = 5;

    const CHARTED_ACCOUNTS = [
        '1' => [
            ['code' => '101', 'user_id' => null, 'account_id' => null, 'name' => 'Cash', 'enabled' => false],
            ['code' => '102', 'user_id' => null, 'account_id' => null, 'name' => 'Petty cash', 'enabled' => false],
            ['code' => '103', 'user_id' => null, 'account_id' => null, 'name' => 'Cash equivalents', 'enabled' => false],
            ['code' => '104', 'user_id' => null, 'account_id' => null, 'name' => 'Short-term investments', 'enabled' => false],
            ['code' => '106', 'user_id' => null, 'account_id' => null, 'name' => 'Accounts receivable', 'enabled' => false],
            ['code' => '107', 'user_id' => null, 'account_id' => null, 'name' => 'Allowance for doubtful accounts', 'enabled' => false],
            ['code' => '109', 'user_id' => null, 'account_id' => null, 'name' => 'Interest receivable', 'enabled' => false],
            ['code' => '110', 'user_id' => null, 'account_id' => null, 'name' => 'Rent receivable', 'enabled' => false],
            ['code' => '111', 'user_id' => null, 'account_id' => null, 'name' => 'Notes receivable', 'enabled' => false],
            ['code' => '119', 'user_id' => null, 'account_id' => null, 'name' => 'Merchandise inventory', 'enabled' => false],
            ['code' => '124', 'user_id' => null, 'account_id' => null, 'name' => 'Office supplies', 'enabled' => false],
            ['code' => '128', 'user_id' => null, 'account_id' => null, 'name' => 'Prepaid insurance', 'enabled' => false],
            ['code' => '129', 'user_id' => null, 'account_id' => null, 'name' => 'Prepaid interest', 'enabled' => false],
            ['code' => '131', 'user_id' => null, 'account_id' => null, 'name' => 'Prepaid rent', 'enabled' => false],
            ['code' => '141', 'user_id' => null, 'account_id' => null, 'name' => 'Long-term Investments', 'enabled' => false],
            ['code' => '151', 'user_id' => null, 'account_id' => null, 'name' => 'Automobiles', 'enabled' => false],
            ['code' => '152', 'user_id' => null, 'account_id' => null, 'name' => 'Accumulated depreciation- Automobiles', 'enabled' => false],
            ['code' => '153', 'user_id' => null, 'account_id' => null, 'name' => 'Trucks', 'enabled' => false],
            ['code' => '154', 'user_id' => null, 'account_id' => null, 'name' => 'Accumulated depreciation-Trucks', 'enabled' => false],
            ['code' => '159', 'user_id' => null, 'account_id' => null, 'name' => 'Library', 'enabled' => false],
            ['code' => '160', 'user_id' => null, 'account_id' => null, 'name' => 'Accumulated depreciation-Library', 'enabled' => false],
            ['code' => '161', 'user_id' => null, 'account_id' => null, 'name' => 'Furniture', 'enabled' => false],
            ['code' => '162', 'user_id' => null, 'account_id' => null, 'name' => 'Accumulated depreciation-Furniture', 'enabled' => false],
            ['code' => '163', 'user_id' => null, 'account_id' => null, 'name' => 'Office Equipment', 'enabled' => false],
            ['code' => '164', 'user_id' => null, 'account_id' => null, 'name' => 'Accumulated depreciation-Office equipment', 'enabled' => false],
            ['code' => '169', 'user_id' => null, 'account_id' => null, 'name' => 'Machinery', 'enabled' => false],
            ['code' => '170', 'user_id' => null, 'account_id' => null, 'name' => 'Accumulated depreciation-Machinery', 'enabled' => false],
            ['code' => '175', 'user_id' => null, 'account_id' => null, 'name' => 'Building', 'enabled' => false],
            ['code' => '176', 'user_id' => null, 'account_id' => null, 'name' => 'Accumulated depreciation-Building', 'enabled' => false],
            ['code' => '179', 'user_id' => null, 'account_id' => null, 'name' => 'Land improvements', 'enabled' => false],
            ['code' => '180', 'user_id' => null, 'account_id' => null, 'name' => 'Accumulated depreciation-Land improvements', 'enabled' => false],
            ['code' => '183', 'user_id' => null, 'account_id' => null, 'name' => 'Land', 'enabled' => false],
            ['code' => '185', 'user_id' => null, 'account_id' => null, 'name' => 'Mineral deposit', 'enabled' => false],
            ['code' => '186', 'user_id' => null, 'account_id' => null, 'name' => 'Accumulated depreciation-Mineral deposit', 'enabled' => false],
            ['code' => '191', 'user_id' => null, 'account_id' => null, 'name' => 'Patents', 'enabled' => false],
            ['code' => '192', 'user_id' => null, 'account_id' => null, 'name' => 'Leasehold', 'enabled' => false],
            ['code' => '193', 'user_id' => null, 'account_id' => null, 'name' => 'Franchise', 'enabled' => false],
            ['code' => '194', 'user_id' => null, 'account_id' => null, 'name' => 'Copyrights', 'enabled' => false],
            ['code' => '195', 'user_id' => null, 'account_id' => null, 'name' => 'Leaseholds improvements', 'enabled' => false],
            ['code' => '196', 'user_id' => null, 'account_id' => null, 'name' => 'Licenses', 'enabled' => false],
            ['code' => '197', 'user_id' => null, 'account_id' => null, 'name' => 'Accumulated amortization', 'enabled' => false],
        ],
        '2' => [
            ['code' => '201', 'user_id' => null, 'account_id' => null, 'name' => 'Accounts payable', 'enabled' => false],
            ['code' => '202', 'user_id' => null, 'account_id' => null, 'name' => 'Insurance payable', 'enabled' => false],
            ['code' => '203', 'user_id' => null, 'account_id' => null, 'name' => 'Interest payable', 'enabled' => false],
            ['code' => '204', 'user_id' => null, 'account_id' => null, 'name' => 'Legal fees payable', 'enabled' => false],
            ['code' => '207', 'user_id' => null, 'account_id' => null, 'name' => 'Office salaries payable', 'enabled' => false],
            ['code' => '208', 'user_id' => null, 'account_id' => null, 'name' => 'Rent payable', 'enabled' => false],
            ['code' => '209', 'user_id' => null, 'account_id' => null, 'name' => 'Salaries payable', 'enabled' => false],
            ['code' => '210', 'user_id' => null, 'account_id' => null, 'name' => 'Wages payable', 'enabled' => false],
            ['code' => '211', 'user_id' => null, 'account_id' => null, 'name' => 'Accrued payroll payable', 'enabled' => false],
            ['code' => '214', 'user_id' => null, 'account_id' => null, 'name' => 'Estimated warranty liability', 'enabled' => false],
            ['code' => '215', 'user_id' => null, 'account_id' => null, 'name' => 'Income taxes payable', 'enabled' => false],
            ['code' => '216', 'user_id' => null, 'account_id' => null, 'name' => 'Common dividend payable', 'enabled' => false],
            ['code' => '217', 'user_id' => null, 'account_id' => null, 'name' => 'Preferred dividend payable', 'enabled' => false],
            ['code' => '218', 'user_id' => null, 'account_id' => null, 'name' => 'State unemployment taxes payable', 'enabled' => false],
            ['code' => '219', 'user_id' => null, 'account_id' => null, 'name' => 'Employee federal income taxes payable', 'enabled' => false],
            ['code' => '221', 'user_id' => null, 'account_id' => null, 'name' => 'Employee medical insurance payable', 'enabled' => false],
            ['code' => '222', 'user_id' => null, 'account_id' => null, 'name' => 'Employee retirement program payable', 'enabled' => false],
            ['code' => '223', 'user_id' => null, 'account_id' => null, 'name' => 'Employee union dues payable', 'enabled' => false],
            ['code' => '224', 'user_id' => null, 'account_id' => null, 'name' => 'Federal unemployment taxes payable', 'enabled' => false],
            ['code' => '225', 'user_id' => null, 'account_id' => null, 'name' => 'FICA taxes payable', 'enabled' => false],
            ['code' => '226', 'user_id' => null, 'account_id' => null, 'name' => 'Estimated vacation pay liability', 'enabled' => false],
            ['code' => '230', 'user_id' => null, 'account_id' => null, 'name' => 'Unearned consulting fees', 'enabled' => false],
            ['code' => '231', 'user_id' => null, 'account_id' => null, 'name' => 'Unearned legal fees', 'enabled' => false],
            ['code' => '232', 'user_id' => null, 'account_id' => null, 'name' => 'Unearned property management fees', 'enabled' => false],
            ['code' => '235', 'user_id' => null, 'account_id' => null, 'name' => 'Unearned janitorial revenue', 'enabled' => false],
            ['code' => '238', 'user_id' => null, 'account_id' => null, 'name' => 'Unearned rent', 'enabled' => false],
            ['code' => '240', 'user_id' => null, 'account_id' => null, 'name' => 'Short-term notes payable', 'enabled' => false],
            ['code' => '245', 'user_id' => null, 'account_id' => null, 'name' => 'Notes payable', 'enabled' => false],
            ['code' => '251', 'user_id' => null, 'account_id' => null, 'name' => 'Long-term notes payable', 'enabled' => false],
            ['code' => '253', 'user_id' => null, 'account_id' => null, 'name' => 'Long-term lease liability', 'enabled' => false],
            ['code' => '255', 'user_id' => null, 'account_id' => null, 'name' => 'Bonds payable', 'enabled' => false],
            ['code' => '258', 'user_id' => null, 'account_id' => null, 'name' => 'Deferred income tax liability', 'enabled' => false],
        ],
        '3' => [
            ['code' => '301', 'user_id' => null, 'account_id' => null, 'name' => 'Owner’s Capital', 'enabled' => false],
            ['code' => '302', 'user_id' => null, 'account_id' => null, 'name' => 'Owner’s Withdrawals', 'enabled' => false],
            ['code' => '307', 'user_id' => null, 'account_id' => null, 'name' => 'Common stock, par value', 'enabled' => false],
            ['code' => '308', 'user_id' => null, 'account_id' => null, 'name' => 'Common stock, no par value', 'enabled' => false],
            ['code' => '309', 'user_id' => null, 'account_id' => null, 'name' => 'Common stock, stated value', 'enabled' => false],
            ['code' => '310', 'user_id' => null, 'account_id' => null, 'name' => 'Common stock dividend distributable', 'enabled' => false],
            ['code' => '311', 'user_id' => null, 'account_id' => null, 'name' => 'Paid-in capital in excess of par value, Common stock', 'enabled' => false],
            ['code' => '312', 'user_id' => null, 'account_id' => null, 'name' => 'Paid-in capital in excess of stated value, No-par common stock', 'enabled' => false],
            ['code' => '313', 'user_id' => null, 'account_id' => null, 'name' => 'Paid-in capital from retirement of common stock', 'enabled' => false],
            ['code' => '314', 'user_id' => null, 'account_id' => null, 'name' => 'Paid in capital, Treasury stock', 'enabled' => false],
            ['code' => '315', 'user_id' => null, 'account_id' => null, 'name' => 'Preferred stock', 'enabled' => false],
            ['code' => '316', 'user_id' => null, 'account_id' => null, 'name' => 'Paid-in capital in excess of par value, Preferred stock', 'enabled' => false],
            ['code' => '318', 'user_id' => null, 'account_id' => null, 'name' => 'Retained earnings', 'enabled' => false],
            ['code' => '319', 'user_id' => null, 'account_id' => null, 'name' => 'Cash dividends', 'enabled' => false],
            ['code' => '320', 'user_id' => null, 'account_id' => null, 'name' => 'Stock dividends', 'enabled' => false],
            ['code' => '321', 'user_id' => null, 'account_id' => null, 'name' => 'Treasury stock, Common', 'enabled' => false],
            ['code' => '322', 'user_id' => null, 'account_id' => null, 'name' => 'Unrealized gain-Equity', 'enabled' => false],
            ['code' => '323', 'user_id' => null, 'account_id' => null, 'name' => 'Unrealized loss-Equity', 'enabled' => false],
        ],
        '4' => [
            ['code' => '401', 'user_id' => null, 'account_id' => null, 'name' => 'Fees earned from product one*', 'enabled' => false],
            ['code' => '402', 'user_id' => null, 'account_id' => null, 'name' => 'Fees earned from product two*', 'enabled' => false],
            ['code' => '403', 'user_id' => null, 'account_id' => null, 'name' => 'Service revenue one*', 'enabled' => false],
            ['code' => '404', 'user_id' => null, 'account_id' => null, 'name' => 'Service revenue two*', 'enabled' => false],
            ['code' => '405', 'user_id' => null, 'account_id' => null, 'name' => 'Commissions earned', 'enabled' => false],
            ['code' => '406', 'user_id' => null, 'account_id' => null, 'name' => 'Rent revenue', 'enabled' => false],
            ['code' => '407', 'user_id' => null, 'account_id' => null, 'name' => 'Dividends revenue', 'enabled' => false],
            ['code' => '408', 'user_id' => null, 'account_id' => null, 'name' => 'Earnings from investments in “blank”', 'enabled' => false],
            ['code' => '409', 'user_id' => null, 'account_id' => null, 'name' => 'Interest revenue', 'enabled' => false],
            ['code' => '410', 'user_id' => null, 'account_id' => null, 'name' => 'Sinking fund earnings', 'enabled' => false],
            ['code' => '413', 'user_id' => null, 'account_id' => null, 'name' => 'Sales', 'enabled' => false],
            ['code' => '414', 'user_id' => null, 'account_id' => null, 'name' => 'Sales returns and allowances', 'enabled' => false],
            ['code' => '415', 'user_id' => null, 'account_id' => null, 'name' => 'Sales discounts', 'enabled' => false],
        ],
        '5' => [
            ['code' => '501', 'user_id' => null, 'account_id' => null, 'name' => 'Amortization expense', 'enabled' => false],
            ['code' => '502', 'user_id' => null, 'account_id' => null, 'name' => 'Depletion expense', 'enabled' => false],
            ['code' => '503', 'user_id' => null, 'account_id' => null, 'name' => 'Depreciation expense-Automobiles', 'enabled' => false],
            ['code' => '504', 'user_id' => null, 'account_id' => null, 'name' => 'Depreciation expense-Building', 'enabled' => false],
            ['code' => '505', 'user_id' => null, 'account_id' => null, 'name' => 'Depreciation expense-Furniture', 'enabled' => false],
            ['code' => '506', 'user_id' => null, 'account_id' => null, 'name' => 'Depreciation expense-Land improvements', 'enabled' => false],
            ['code' => '507', 'user_id' => null, 'account_id' => null, 'name' => 'Depreciation expense-Library', 'enabled' => false],
            ['code' => '508', 'user_id' => null, 'account_id' => null, 'name' => 'Depreciation expense-Machinery', 'enabled' => false],
            ['code' => '509', 'user_id' => null, 'account_id' => null, 'name' => 'Depreciation expense-Mineral deposit', 'enabled' => false],
            ['code' => '510', 'user_id' => null, 'account_id' => null, 'name' => 'Depreciation expense-Office equipment', 'enabled' => false],
            ['code' => '511', 'user_id' => null, 'account_id' => null, 'name' => 'Depreciation expense-Trucks', 'enabled' => false],
            ['code' => '520', 'user_id' => null, 'account_id' => null, 'name' => 'Office salaries expense', 'enabled' => false],
            ['code' => '521', 'user_id' => null, 'account_id' => null, 'name' => 'Sales salaries expense', 'enabled' => false],
            ['code' => '522', 'user_id' => null, 'account_id' => null, 'name' => 'Salaries expense', 'enabled' => false],
            ['code' => '523', 'user_id' => null, 'account_id' => null, 'name' => '“Blank” wages expense', 'enabled' => false],
            ['code' => '524', 'user_id' => null, 'account_id' => null, 'name' => 'Employees’ benefits expense', 'enabled' => false],
            ['code' => '525', 'user_id' => null, 'account_id' => null, 'name' => 'Payroll taxes expense', 'enabled' => false],
            ['code' => '530', 'user_id' => null, 'account_id' => null, 'name' => 'Cash over and Short', 'enabled' => false],
            ['code' => '531', 'user_id' => null, 'account_id' => null, 'name' => 'Discounts lost', 'enabled' => false],
            ['code' => '532', 'user_id' => null, 'account_id' => null, 'name' => 'Factoring fee expense', 'enabled' => false],
            ['code' => '533', 'user_id' => null, 'account_id' => null, 'name' => 'Interest expense', 'enabled' => false],
            ['code' => '535', 'user_id' => null, 'account_id' => null, 'name' => 'Insurance expense-Delivery equipment', 'enabled' => false],
            ['code' => '536', 'user_id' => null, 'account_id' => null, 'name' => 'Insurance expense-Office equipment', 'enabled' => false],
            ['code' => '540', 'user_id' => null, 'account_id' => null, 'name' => 'Rent expense', 'enabled' => false],
            ['code' => '541', 'user_id' => null, 'account_id' => null, 'name' => 'Rent expense-Office space', 'enabled' => false],
            ['code' => '542', 'user_id' => null, 'account_id' => null, 'name' => 'Rent expense-Selling space', 'enabled' => false],
            ['code' => '543', 'user_id' => null, 'account_id' => null, 'name' => 'Press rental expense', 'enabled' => false],
            ['code' => '544', 'user_id' => null, 'account_id' => null, 'name' => 'Truck rental expense', 'enabled' => false],
            ['code' => '545', 'user_id' => null, 'account_id' => null, 'name' => '“Blank” rental expense', 'enabled' => false],
            ['code' => '550', 'user_id' => null, 'account_id' => null, 'name' => 'Office supplies expense', 'enabled' => false],
            ['code' => '551', 'user_id' => null, 'account_id' => null, 'name' => 'Store supplies expense', 'enabled' => false],
            ['code' => '552', 'user_id' => null, 'account_id' => null, 'name' => '“Blank” supplies expense', 'enabled' => false],
            ['code' => '555', 'user_id' => null, 'account_id' => null, 'name' => 'Advertising expense', 'enabled' => false],
            ['code' => '556', 'user_id' => null, 'account_id' => null, 'name' => 'Bad debts expense', 'enabled' => false],
            ['code' => '557', 'user_id' => null, 'account_id' => null, 'name' => 'Blueprinting expense', 'enabled' => false],
            ['code' => '558', 'user_id' => null, 'account_id' => null, 'name' => 'Boat expense', 'enabled' => false],
            ['code' => '559', 'user_id' => null, 'account_id' => null, 'name' => 'Collection expense', 'enabled' => false],
            ['code' => '561', 'user_id' => null, 'account_id' => null, 'name' => 'Concessions expense', 'enabled' => false],
            ['code' => '562', 'user_id' => null, 'account_id' => null, 'name' => 'Credit card expense', 'enabled' => false],
            ['code' => '563', 'user_id' => null, 'account_id' => null, 'name' => 'Delivery expense', 'enabled' => false],
            ['code' => '564', 'user_id' => null, 'account_id' => null, 'name' => 'Dumping expense', 'enabled' => false],
            ['code' => '566', 'user_id' => null, 'account_id' => null, 'name' => 'Equipment expense', 'enabled' => false],
            ['code' => '567', 'user_id' => null, 'account_id' => null, 'name' => 'Food and drinks expense', 'enabled' => false],
            ['code' => '568', 'user_id' => null, 'account_id' => null, 'name' => 'Gas and oil expense', 'enabled' => false],
            ['code' => '571', 'user_id' => null, 'account_id' => null, 'name' => 'General and administrative expense', 'enabled' => false],
            ['code' => '572', 'user_id' => null, 'account_id' => null, 'name' => 'Janitorial expense', 'enabled' => false],
            ['code' => '573', 'user_id' => null, 'account_id' => null, 'name' => 'Legal fees expense', 'enabled' => false],
            ['code' => '574', 'user_id' => null, 'account_id' => null, 'name' => 'Mileage expense', 'enabled' => false],
            ['code' => '576', 'user_id' => null, 'account_id' => null, 'name' => 'Miscellaneous expense', 'enabled' => false],
            ['code' => '577', 'user_id' => null, 'account_id' => null, 'name' => 'Mower and tool expense', 'enabled' => false],
            ['code' => '578', 'user_id' => null, 'account_id' => null, 'name' => 'Operating expense', 'enabled' => false],
            ['code' => '579', 'user_id' => null, 'account_id' => null, 'name' => 'Organization expense', 'enabled' => false],
            ['code' => '580', 'user_id' => null, 'account_id' => null, 'name' => 'Permits expense', 'enabled' => false],
            ['code' => '581', 'user_id' => null, 'account_id' => null, 'name' => 'Postage expense', 'enabled' => false],
            ['code' => '582', 'user_id' => null, 'account_id' => null, 'name' => 'Property taxes expense', 'enabled' => false],
            ['code' => '583', 'user_id' => null, 'account_id' => null, 'name' => 'Repairs expense', 'enabled' => false],
            ['code' => '584', 'user_id' => null, 'account_id' => null, 'name' => 'Selling expense', 'enabled' => false],
            ['code' => '585', 'user_id' => null, 'account_id' => null, 'name' => 'Telephone expense', 'enabled' => false],
            ['code' => '587', 'user_id' => null, 'account_id' => null, 'name' => 'Travel and entertainment expense', 'enabled' => false],
            ['code' => '590', 'user_id' => null, 'account_id' => null, 'name' => 'Utilities expense', 'enabled' => false],
            ['code' => '591', 'user_id' => null, 'account_id' => null, 'name' => 'Warranty expense', 'enabled' => false],
            ['code' => '595', 'user_id' => null, 'account_id' => null, 'name' => 'Income taxes expense', 'enabled' => false],
        ],
    ];
}
